name: Release

on:
  push:
    branches:
      - main

env:
  LEFTHOOK: 0
  CI: true

permissions:
  contents: write
  packages: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: â³ Release
    runs-on: ubuntu-latest
    steps:
      # - name: ðŸ¦– Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.12.1

      - name: ðŸ”» Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ðŸƒ Run Node and NPM setup
        uses: ./.github/actions/setup-project

      - name: ðŸ“„ Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@tutods:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: ðŸ“¦ Create Release
        id: changesets
        uses: changesets/action@v1
        env:
          LEFTHOOK: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          createGithubReleases: true
          version: pnpm version:create
          publish: pnpm version:publish --no-git-checks --tag latest
          title: 'ðŸ¤– ci(changesets): :package: version packages'
          commit: 'ci(changesets): version packages'
    
#      - name: ðŸ“¤ Publish version
#        if: ${{ steps.changesets.outputs.hasChangesets == false }}
#        run: |
#          echo ${{steps.changesets.outputs.hasChangesets}}
#          pnpm version:publish
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
